version: 0.2
phases:
  pre_build:
    commands:
       - sam package --template-file template.yml --output-template-file package.yml --s3-bucket sam-sourcecode-gmthomp
    commands:
  artifacts:
    files:
      - package.yml